// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoaFmbL3m0z6tIDOMNEwBGZAvtNnQuwg8',
    appId: '1:894366798660:web:7a292bf06328c5ed9b7d11',
    messagingSenderId: '894366798660',
    projectId: 'jadty-63ad6',
    authDomain: 'jadty-63ad6.firebaseapp.com',
    storageBucket: 'jadty-63ad6.firebasestorage.app',
    measurementId: 'G-HP0BZFBF87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJQkG3U7BGNsEmu0tvsQQUrafGTG6oX8s',
    appId: '1:894366798660:android:ff13a72fb35ab5559b7d11',
    messagingSenderId: '894366798660',
    projectId: 'jadty-63ad6',
    storageBucket: 'jadty-63ad6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUhiGvMnbVqZaeweDXGkhqFJzKkozeiFY',
    appId: '1:894366798660:ios:300ce8c1ceade7639b7d11',
    messagingSenderId: '894366798660',
    projectId: 'jadty-63ad6',
    storageBucket: 'jadty-63ad6.firebasestorage.app',
    iosBundleId: 'com.jadty.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUhiGvMnbVqZaeweDXGkhqFJzKkozeiFY',
    appId: '1:894366798660:ios:8361c2796532440b9b7d11',
    messagingSenderId: '894366798660',
    projectId: 'jadty-63ad6',
    storageBucket: 'jadty-63ad6.firebasestorage.app',
    iosBundleId: 'com.example.jadty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoaFmbL3m0z6tIDOMNEwBGZAvtNnQuwg8',
    appId: '1:894366798660:web:56f1609182db5ce59b7d11',
    messagingSenderId: '894366798660',
    projectId: 'jadty-63ad6',
    authDomain: 'jadty-63ad6.firebaseapp.com',
    storageBucket: 'jadty-63ad6.firebasestorage.app',
    measurementId: 'G-9N38DVV23W',
  );
}
